mainsail-crew/MainsailOS

- src/modules/mainsail/filesystem/root/etc/nginx/conf.d/common_vars.conf
- src/modules/mainsail/filesystem/root/etc/nginx/conf.d/upstreams.conf
- src/modules/mainsail/filesystem/root/etc/nginx/sites-available/mainsail
This is the simplest way I could think of to remove the upstream dependency from each clients server configuration.
This way, if another web client wants to use the same upstream configuration - they can - without conflicts.
I also moved the `$http_upgrade` map to common configuration, altho this isn't strictly necessary.
> chore: moves $httpupgrade and upstream servers to common config

- src/modules/klipper_moonraker/filesystem/home/pi/klipper_config/moonraker.conf
This will allow users of mainsailos moving forward to effectively use fluidd in a remote hosted environment, in a secure way.
> feat: allow the app.fluidd.xyz origin

- src/modules/mjpgstreamer/filesystem/home/root/bin/webcamd
string '/dev/video' is 10 characters; use 1st field, 11th character till EOL for numerical sort:
ls /dev/video* | sort -nk1.11
/dev/video2
/dev/video10
rather than
ls /dev/video* | sort
/dev/video10
/dev/video2
> sort video devices numerical

- src/modules/mainsail/filesystem/home/pi/klipper_config/mainsail.cfg
add home and temperature check to the default macros. This will avoid errors if PAUSE or RESUME is executed while not homed or extruder below minimum temperature.
> macro: add home and temp check

- src/modules/mainsail/filesystem/home/pi/klipper_config/mainsail.cfg
Change the rename_existing name for a better sorting result at the help command. Also add a macro description for the new klipper description property  
> macro: add description and change rename_existing

- src/modules/mainsail/filesystem/home/pi/klipper_config/mainsail.cfg
This is added to support the specified parameter of the org klipper gcode command
> get VELOCITY parameter if specified and add it to RESUME_BASE

- src/modules/mainsail/filesystem/home/pi/klipper_config/mainsail.cfg
remove the save and restore of the gcode state as it is already paar of the base macros
> remove gcode state

- src/modules/serialcomm/start_chroot_script
BUGFIX: Fixed Typo in start_chroot_script of serialcomm Module
> BUGFIX: Fixed Typo in start_chroot_script of serialcomm Module

- src/modules/is_req_preinstall/config
- src/modules/klipper/config
Updated Inputshaper Dependencies to python3
python3-numpy, python3-matplotlib
Moved Dependency python-matplotlib to klipper module dependencies
> refactor: updated input shaper dependencies to python3

- Makefile
CustomPiOS has a naming convention for Image names.
Therefor manual build via Makefile will exit with error.
Renaming the Image file according to Naming convention fixes this.
> fix(build): fixes error in Makefile

- .editorconfig
Added a .editorconfig file for easier style/rule sharing to Contributors.
Also helps to avoid "missing empty new line at end of file" git error message.
> feat: added .editorconfig

- src/modules/mainsail/filesystem/root/etc/logrotate.d/rsyslog
- src/modules/mainsail/filesystem/root/etc/nginx/sites-available/mainsail
- src/modules/mainsail/start_chroot_script
- src/modules/mjpgstreamer/filesystem/root/etc/logrotate.d/webcamd
Disabled logging for 'webcam*' nginx proxy
Changed nginx logrotate 'rotate' from 14 to 2
Changed webcamd logging, rotate 2 and limit to 32M
Changed rsyslog logrotate 'rotate' from 4 to 2
and limit from 256M to 128M and daily instead of weekly
> feat: changed logging and logrotate behavior

- src/modules/mainsail/filesystem/root/etc/nginx/sites-available/mainsail
When uStreamer is behind an Nginx proxy,
it's buffering behavior introduces latency into the video stream.
For Details see: https://github.com/pikvm/ustreamer#nginx
> fix(ustreamer): disable buffering on webcam proxy entries

- src/modules/mainsail/config
Used https://github.com/meteyou/mainsail instead of
https://github.com/mainsail-crew/mainsail
> fix(mainsail): changed download url to mainsail-crew url

- README.md
The screenshot was referencing an image URL that no longer exists. This PR references the screenshot in the docs repo, the same as other Mainsail repos.
> Fix image URL for screenshot

- src/modules/mainsail/filesystem/home/pi/klipper_config/mainsail.cfg
Adds an `M106 S0` command to `CANCEL_PRINT` macro in order to stop the print cooling fan!
(Note: file has also been automatically reformatted with the exiting ".editorconfig" in the repo!)
Signed-off-by: Pedro Lamas <pedrolamas@gmail.com>
> feat: stop part fan on CANCEL_PRINT

- src/config
- src/modules/sonar/config
- src/modules/sonar/start_chroot_script
To prevent connection problems, it uses
https://github.com/mainsail-crew/sonar
This should fix #47
> feat: add sonar by default to image

- src/modules/is_req_preinstall/config
- src/modules/klipper/config
- src/modules/klipper/start_chroot_script
Klipper: Build venv with py3, updates dependencies accordingly.
Input Shaper: Uses now fixed version <=1.21.4 from piwheels
> chore(klipper): update klipper and input shaper to py3

- src/modules/crowsnest/config
- src/modules/crowsnest/start_chroot_script
Should fix error that results in unusable moonraker.conf
> fix(crowsnest): fix install of crowsnest

- src/modules/moonraker/filesystem/home/pi/klipper_config/moonraker.conf
With the upcoming v2.2.0 release of Mainsail, Mainsail will support Moonraker announcements. Therefore it makes sense to already add Mainsail to the list of subscriptions by default.
Signed-off-by: Dominik Willner th33xitus@gmail.com
> feat(moonraker.conf): add mainsail subscription to announcements

- src/modules/mainsail/filesystem/home/pi/klipper_config/mainsail.cfg
Removes any reference to `error_message` variable in the `on_gcode_error` block as this Klipper variable was removed before merging into master.
When this block of code runs the print will already have been stopped, so I do believe it will be safe to just call `CANCEL_PRINT` whatever the error was.
Related Klipper docs: https://www.klipper3d.org/Config_Reference.html#virtual_sdcard
Related to #116
Signed-off-by: Pedro Lamas <pedrolamas@gmail.com>
> fix: correct on_error_gcode in mainsail.cfg

- src/modules/is_req_preinstall/config
- src/modules/is_req_preinstall/start_chroot_script
- src/modules/klipper/config
- src/modules/klipper/filesystem/root/etc/systemd/system/klipper.service
- src/modules/klipper/start_chroot_script
Style: add new header
Style: refactored to match shellcheck requirements.
Improved:
Inherited error trap.
Set fallback lang to C.
Set DEBIAN_FRONTEND to noninteractive if not noninteractive.
Replaced apt install with check_install_pkgs
Fix: Use correct network-online.target instead network.target
> refactor(klipper): refactor klipper and is-pre-install module

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Adds Templates for Feature Request and Bug Issues.
> chore: add Issue Templates

- src/modules/piconfig/filesystem/root/boot/config.txt
This should fix errors with installers of Raspi Screens,
they expect [all] section at last for appending special
configurations.
> fix(config.txt): fix configuration errors with attached screens

- src/config
- src/modules/postrename/config
- src/modules/postrename/filesystem/root/postrename
- src/modules/postrename/start_chroot_script
This module allows to rename the username in
rpi-imager, it should fix all neccessary stuff
to run like intended before rename.
> feat: add postrename module

- src/modules/moonraker/start_chroot_script
Dependency 'wireless-tools' needed by moonraker for 'iwgetid'
> chore: add wireless-tools as moonraker dependency

- src/modules/is_req_preinstall/config
Input Shaper now needs libatlas3-base and libatlas-base-dev
as additional dependencies
> chore: add additional Input shaper dependencies

- src/modules/postrename/config
- src/modules/postrename/filesystem/root/postrename
- src/modules/postrename/start_chroot_script
This should fix #136
Due moving venv's with virtualenv,
some path aren't get changed.
Now pycache will be deleted and
shebang lines manipulated to match paths
> fix: fix errors in moved venvs

- src/config
- src/modules/net/config
- src/modules/net/filesystem/boot/WiFi-README.txt
- src/modules/net/filesystem/boot/wpa_supplicant.conf.example
- src/modules/net/filesystem/etc/systemd/system/disable-wifi-pwr-mgmt.service
- src/modules/net/filesystem/etc/udev/rules.d/070-wifi-powersave.rules
- src/modules/net/filesystem/usr/local/bin/pwrsave
- src/modules/net/filesystem/usr/local/bin/pwrsave-udev
- src/modules/net/start_chroot_script
This is more a workaround as a fix.
Raspberry Foundation changed handling of wpa_supplicant.conf.
Also KlipperScreen uses wpa_cli which overrides softlink to txt.
fixes #134
> fix: fixes error unusable wpa_supplicant.txt

- src/modules/net/filesystem/boot/WiFi-README.txt
Signed-off-by: John O'Shaughnessy <oshinfo@cloud7.org>
> docs: Update README for improved readability

- .github/workflows/BuildRaspiOS.yml
- .github/workflows/ReleaseRaspiOS.yml
> chore: rework build workflow with source image cache

- src/modules/is_req_preinstall/config
- src/modules/klipper/config
libusb-1.0 has been renamed to libusb-1.0-0
numpy is available as piwheels package with version 1.23.2
(released 2022-08-14)
> chore: update versions according to bullseye

- src/modules/postrename/filesystem/root/postrename
Obsolete option '--relocateable' introduces error. Removed virtualenv relocate,
only remove pycache and fix hardcoded paths
> fix: fix postrename script

- src/modules/mainsail/filesystem/root/etc/nginx/sites-available/mainsail
> refactor: deactivate IPv6 in nginx per default

- .github/workflows/ShellCheck.yml
This is a combined fix/improvement
Fixes Error that files without script extension (.sh) being ignored.
Improved Job structure, dropped usage of matrix to seperate checks.
Added Summary Messages.
> chore: improved shellcheck lint

- src/modules/piconfig/filesystem/tmp/msos_config.txt
Removes dtoverlays for vc4-fkms-v3d, appears to be problematic in some setups
> chore: removes fkms overlays

- patches/Readme.md
- patches/patch.sh
- src/modules/net/config
- src/modules/net/start_chroot_script
> fix: fix syntax error in net module

- config/armbian/default
- config/armbian/orangepi3lts
- config/armbian/orangepi4lts
- src/modules/armbian_net/config
- src/modules/armbian_net/filesystem/root/boot/network_config.txt.template
- src/modules/armbian_net/filesystem/root/etc/systemd/system/network-configurator.service
- src/modules/armbian_net/start_chroot_script
- src/modules/is_req_preinstall/config
- src/modules/klipper/config
- src/modules/opiconfig/config
- src/modules/opiconfig/start_chroot_script
This builds an basic Image for
Orange Pi 3 LTS and 4 LTS
Includes:
- mainsail
- klipper
- moonraker
- timelapse
- crowsnest
- sonar
- Input Shaper PreInstall
- Hardware preconfiguration
> feat: add Orange Pi 3 and 4 LTS

- .github/workflows/Release.yml
this PR fix the rpi-imager json workflow to parse extract_size & image_download_size as an integer
> fix: fix rpi-imager json value format for int values

- patches/Readme.md
- patches/udev-fix.sh
- src/modules/udev_fix/start_chroot_script
This is needed to also patch if version is from raspberry which is named '247.3-7+rpi1+deb11u2'
Also includes fix for typo in previous patch
> fix: fix udev for version 'rp1+deb11u2'

- patches/udev-fix.sh
Version was checkt before update, but should be checked after.
Can be merged without test builds, Image isnt affected by that.
> fix: fix error in udev-fix.sh

- README.md
This PR resolves issue #230 by directing users to the updated MainsailOS documentation. It also updates the repository links for Klipper and Mainsail after their relocation to new organizations.
> fix: broken README link to Pi imager

- config/armbian/orangepi3lts
- config/armbian/orangepi4lts
- config/orangepi/orangepi_zero2
This PR only adds _bullseye in the download URLs, because I added Bookworm images in the armbian-builds repo.
> chore: update download urls for armbian & orangepi

- src/modules/postrename/filesystem/root/postrename
Fix typo in L171, which leads to an created symlink with double slashes.
> fix: fix typo in tools_dir var, Line171

- config/armbian/default
- src/modules/armbian_net/config
- src/modules/armbian_net/start_chroot_script
This should fix not working network configuration via `network_config.txt`
The script has changed by armbian but misses the crutial package `net-tools`.
Also some kernel versions on Orange Pi 3 LTS models drops wifi interface.
This is fixed by kernel 6.1.53. To get that kernel I reimplemented the `pkgupgrade`module for armbian images.
> fix: fix wifi connectivity

- src/modules/armbian/start_chroot_script
- src/modules/mainsailos/start_chroot_script
To get mainsail release shown in moonraker we need that 'hacky' solution
> fix: fix armbian-release file error

- src/modules/armbian/start_chroot_script
- src/modules/orangepi/start_chroot_script
Since we applied PR #241 and #242,
this function always doesnt give the right value,
which leads to unwanted behaviour in enabling SPI during build.
As we no longer rename the release file,
we have to use its original location in '/etc/armbian-release' ( Or '/etc/orangepi-release' if Opi Image is used )
> fix: fix 'is_board_type' function

- config/raspberry/rpi32
- config/raspberry/rpi64
After Bullseye images moved to 'oldstable' branch, we need to alter the URLs to 'legacy' images and checksums
> fix: fix Torrent and Checksum download URLs

- src/modules/klipper/filesystem/root/etc/systemd/system/klipper.service
Seems the used alias, which is uneccessary at all, leads to a failing build in some configurations.
This should fix #245
> fix: removing 'klippy' alias

- src/modules/mainsailos/config
Adding `python3-opencv` package to base image to shorten obico install
> feat: add python3-opencv for obico

- .github/label-actions.yml
This PR only update the text of the Issue-Tracker bot for "not on GitHub" and change it to "not an Issue"
> chore: update issue bot text

- src/modules/armbian/filesystem/root/etc/update-motd.d/10-mainsailos
- src/modules/orangepi/filesystem/root/etc/update-motd.d/10-mainsailos
Due #241 the motd will not be updated as intended.
Files are not moved as in the past, so they can not be sourced.
This leads to an empty 'version' description.
> fix: fix motd on armbian and orange pi based images

- .github/actions/build/action.yml
- .github/workflows/BuildImages.yml
- .github/workflows/Release.yml
This PR fixes the annotations about 'actions/cache@v3' and 'actions/upload-artifact@v3'.
Since this particular versions use Node 16 which are marked as depricated,
We had to update to latest versions.
These are in particular 'actions/cache' in version v4.0.0 and
'actions/upload-artifact' in version v4.3.1.
These versions are shown in github marketplace if you click on 'use latest'
> fix(ci): Fix annotations from actions

- src/modules/moonraker/start_chroot_script
Replace `PKGLIST` with `PACKAGES` in moonraker module script, following the rename here: https://github.com/Arksine/moonraker/commit/247640cc27fd75bc657266db44f4a26769309e7e
This change in the moonraker install script was causing a failure to run this module's script, resulting in image build failures.
> fix(moonraker): PKGLIST variable rename

- .github/workflows/release.yml
- config.yml
This PR adds a new attribute to the `config.yml` to allow test images, which will be not released.
Just add the parameter `build_only: True` to a image definition in the `config.yml` like that:
```yaml
- name: raspberry_pi-arm64-ks-bookworm
type: raspberry
build_only: True
...
```
Images with this value will be just executed/build in the PR builds, but will be skipped during the release workflow.
> ci: add attribute to config.yml to add "build_only" images

- modules/raspberry/11-fix-wifi
Per default, wifi is blocked and disabled on rpi os lite. This PR enable it per default, that headless_nm can use it.
> fix: enable wifi per default on rpi sbcs

- .github/workflows/build.yml
- .github/workflows/release.yml
This PR fix the parsing of the array to copy the special modules in the build and release workflow
> fix: fix parsing array to copy special modules

- modules/generic/32-canbus
- modules/generic/files/canbus/10-can.rules
- modules/generic/files/canbus/25-can.network
This PR adds the CANBUS support per default on every image. It adds the CANBUS settings like this guide: https://canbus.esoterical.online/Getting_Started.html#network-service-can-speeds-and-transmit-queue-length
A big thx to @Esoterical for this very good guide!
> feat: add CANBUS support

- modules/generic/files/canbus/25-can.network
This option seems to be causing problems for 6.12.47 based raspiOS. I removed it, because Esotherical removed it also from his guide.
https://github.com/Esoterical/voron_canbus/commit/0d7db1ac5db5969a3223fe8982987d01e7f48800
> fix(Canboot): Removed `RestartSec=0.1s` from the 25-can.network config.
