mainsail-crew/MainsailOS

- src/modules/updater/config
- src/modules/updater/filesystem/root/usr/local/bin/mainsailos-updater
- src/modules/updater/start_chroot_script
Add a CLI updater script to check and update klipper and moonraker. Addition of Mainsail updates will be added once a method to determine version of mainsail for the check is found.
> Add MainsailOS CLI updater module

- src/modules/updater/filesystem/root/usr/local/bin/mainsailos-updater
Add coloring to updater to make it easier to see if something is or is not up to date.
Add functions to upgrade the updater to provide easier end user functionality.
Add changelog functions to dump commit messages between current and latest commits
> Improve updater

- src/modules/klipper_moonraker/filesystem/home/pi/klipper_config/moonraker.conf
- src/modules/mainsail/filesystem/home/pi/klipper_config/.mainsail.json
- src/modules/mainsail/filesystem/home/pi/klipper_config/gui.json
add update manger to moonraker.conf
rename gui.json to .mainsail.json
> updates for mainsail v0.4.0

- src/modules/klipper_moonraker/filesystem/home/pi/klipper_config/moonraker.conf
- src/modules/mainsail/filesystem/home/pi/klipper_config/mainsail.cfg
- src/modules/mainsail/filesystem/root/etc/nginx/sites-available/mainsail
add cors_domains for my.mainsail.xyz & *.local
add PAUSE & RESUME macros to mainsail.cfg
remove upload limit in nginx
merge nginx locations
> Update mainsail configs

- src/modules/mainsail/filesystem/home/pi/klipper_config/mainsail.cfg
Update CANCEL_PRINT following the discussion in klipper PR#4366 and change the exruder check from temperature to the status added by klipper PR #4366
> update macros because of klipper PR #4366 and PR #4362

- README.md
Signed-off-by:  Christoph Frei <fryakatkop@gmail.com>
> improve reamde.md

- src/config
- src/modules/is_req_preinstall/start_chroot_script
Added Environment Variable to Speed up numpy compile times.
Compile time barely affected on gh actions, local depending on CPU Cores.
> Speed up numpy Compile Time

- .github/workflows/ReleaseRaspiOS.yml
- src/config
Release Workflow will also generate a sha256sum file and it will be downloadable from the release.
Also fixed Typo in config file.
> Implementing sha256 Checksum

- .github/workflows/BuildRaspiOS.yml
- .github/workflows/ReleaseRaspiOS.yml
- Makefile
- src/image/2021-03-04-raspios-buster-armhf-lite.zip.sha1
- src/image/2021-12-02-raspios-buster-armhf-lite.zip.sha256
* To match with Raspberry Pi OS (Legacy)
* See https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-legacy
> fix(build): Updated download paths

- src/modules/mainsail/filesystem/root/etc/nginx/sites-available/mainsail
Signed-off-by: Mikkel Schmidt <mikkel.schmidt@gmail.com>
> Enable ipv6 support in nginx

- src/modules/mainsail/filesystem/root/etc/nginx/sites-available/mainsail
Should fix wrong display of downloadsize
> fix: added http1.1 to moonraker api reverse proxy location

- .editorconfig
> chore: updated .editorconfig for yml files

- src/modules/moonraker/filesystem/home/pi/klipper_config/moonraker.conf
Updating moonraker.conf according to
https://github.com/Arksine/moonraker/issues/410
> chore: update moonraker.conf

- src/modules/mainsail/filesystem/home/pi/klipper_config/mainsail.cfg
Signed-off-by: Dominik Willner <th33xitus@gmail.com>
> refactor(mainsail.cfg): substituting `/home/pi` with `~`

- src/modules/mainsail/filesystem/home/pi/klipper_config/mainsail.cfg
> feat: add on_error_gcode to mainsail.cfg

- src/modules/sonar/config
- src/modules/sonar/start_chroot_script
This should fix missing moonraker update_manager entry
> fix(sonar): fix sonar install

- .github/FUNDING.yml
Add Funding informations for Mainsail project
> chore: add funding informations

- README.md
> chore(docs): fix urls, add includes

- src/modules/crowsnest/config
- src/modules/crowsnest/start_chroot_script
Updates crowsnest module according to changes due
https://github.com/mainsail-crew/crowsnest/commit/6071c6fc769dbda8ab18aa16e46fdcba28d8288c
> chore(crowsnest): update crowsnest module

- README.md
- src/modules/mainsailos/config
- src/modules/mainsailos/start_chroot_script
Added CanBoot Dependency to Base Image.
> feat: add python3-serial CanBoot dependency

- src/config
- src/modules/postrename/filesystem/root/postrename
- src/modules/timelapse/config
- src/modules/timelapse/filesystem/home/pi/klipper_config/timelapse_template.txt
- src/modules/timelapse/start_chroot_script
This adds moonraker-timelapse plugin to image.
> feat: add timelapse module

- src/config
> chore: bump version to 0.7.0

- src/modules/moonraker/filesystem/home/pi/klipper_config/moonraker.conf
Signed-off-by: Dominik Willner [th33xitus@gmail.com](mailto:th33xitus@gmail.com)
> refactor: add `enable_auto_refresh: True`

- .github/workflows/stale.yml
> chore: add workflow to close stale issues / pull requests

- src/modules/net/filesystem/boot/WiFi-README.txt
> refactor: minor language edits in wifi-readme.txt

- src/config
> chore: bump version to v0.7.1

- .github/workflows/BuildRaspiOS.yml
> chore: only build an image on push in master/develop branch

- config/raspberry/rpi64
> chore: add Raspberry 64bit config

- .github/workflows/ShellCheck.yml
This should fix errors of shellcheck action
> fix(lint): should fix shellcheck warnings

- src/modules/net/start_chroot_script
Should fix Shellcheck errors SC1091 and SC2129
> fix: fix shellcheck errors in net module

- .github/workflows/BuildImages.yml
> chore: upload failed logfile

- .github/workflows/BuildImages.yml
> fix: set wrong source path

- src/modules/armbian/config
- src/modules/armbian/end_chroot_script
- src/modules/armbian/filesystem/root/etc/update-motd.d/10-mainsailos
- src/modules/armbian/start_chroot_script
This is preperation work for upcomming armbian releases
> chore: add armbian module

- src/modules/piconfig/filesystem/root/boot/config.txt
> fix: add otg_mode=1 for CM4 in config.txt

- src/modules/timelapse/start_chroot_script
> fix: fixes error setting link to macro

- .github/CODE_OF_CONDUCT.md
- .github/DEVELOPER_CERTIFICATE_OF_ORIGIN.md
- CONTRIBUTING.md
- README.md
> docs: adds faq section

- .github/workflows/BuildImages.yml
> chore: remove github-token for build action

- .github/label-actions.yml
- .github/workflows/label-actions.yml
> chore: add "not-on-Github" bot for issues

- src/modules/armbian/filesystem/root/etc/update-motd.d/10-mainsailos
- src/modules/net/filesystem/usr/local/bin/pwrsave-udev
Fixes SC2317 in armbian module and
SC2086 in net module
> fix: fix shellcheck errors

- src/modules/piconfig/filesystem/tmp/msos_config.txt
> feat: enable I2C by default

- src/modules/armbian/start_chroot_script
This only applies if service exists and armbian devices.
> chore: disable unattended-upgrades service

- config/raspberry/default
- src/modules/crowsnest/config
- src/modules/crowsnest/start_chroot_script
According to changes in installer, update crowsnest module for camera-streamer version.
Will be functional in v4 release of crowsnest.
> chore: update crowsnest module

- src/modules/piconfig/filesystem/tmp/msos_config.txt
Also removed `camera_auto_detect`
> fix: remove legacy cam stack

- .github/workflows/Release.yml
This will fix the "node12" issue in the workflow.
> ci(release): update publish release action

- .github/workflows/BuildImages.yml
Surpress another image build if release is running.
> chore(ci): skip build on push to master branch

- .github/workflow_config.yml
- config/raspberry/rpi64-ks
- src/modules/klipperscreen/config
- src/modules/klipperscreen/filesystem/tmp/ks_update_entry.txt
- src/modules/klipperscreen/start_chroot_script
- src/modules/postrename/filesystem/root/postrename
Adds KlipperScreen to an Image if configured.
Adds a RPI64 build to testbuilds, but skips on release.
> feat(ci): add KlipperScreen module

- config/raspberry/default
- config/raspberry/rpi32
- config/raspberry/rpi64
- config/raspberry/rpi64-ks
Updates urls and uses latest bullseye image
> chore: update urls and base image version

- config/armbian/default
- config/orangepi/default
- config/raspberry/default
As recommended from guysoft, change base module to standalone order
This will do specific cleanup tasks recommended by custompios at build finish
> chore: change module order

- .github/workflows/build.yml
- .github/workflows/release.yml
This PR improve the check for special modules in the Build & Release workflow.
Error in the CB1 workflow without special modules: https://github.com/mainsail-crew/MainsailOS/actions/runs/15530002923/job/43716753049#step:10:23
> fix: improve special modules check in build & release workflow
